### ISSUE TITLE
Docker failed to resolve source metadata

### ISSUE THREAD

**Issue by yannnnay** [skjerns/3dprintyourbrain#5]
Hello there,

When I try to build my docker I get the following error: ERROR: failed to solve: freesurfer/freesurfer:7.4.1: failed to resolve source metadata for docker.io/freesurfer/freesurfer:7.4.1: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Afreesurfer%2Ffreesurfer%3Apull&service=registry.docker.io: 401 Unauthorized.

As I am rather novice with Docker that could completely be on my side, but do you have any idea of what could have gone wrong ?

**Comment by skjerns** [comment]
Mh, I just rebuilt my container with no problem - this must be a problem on your side?

According to a quick google this might be due to incorrect proxy settings: https://forums.docker.com/t/failed-with-status-401-unauthorized/11023/2

**Comment by yannnnay** [comment]
Yes something was off with my docker account and it run perfectly now, thanks a lot
