### ISSUE TITLE
 : invalid option

### ISSUE THREAD

**Issue by yannnnay** [skjerns/3dprintyourbrain#6]
Hi,

I have been running into the same issue everytime i try to run the script 3dprintedbrain. 
"docker run 3dprintedbrain subject.nii
: invalid option"
I have been trying different ways, making sure subject.nii was in the folder. I tried to directly run the command from inside the container.
I tried different syntax in my powershell using " " for paths but still it doesn't work.

Have you ever run into a simular issue ?

**Comment by skjerns** [comment]
What exactly is the output you get?

This sounds like a PowerShell issue?

**Comment by skjerns** [comment]
Also this is not the correct command, the are parameters missing

Have you tried Chagpt? It can do miracles with helping bash and ps scrpts

**Comment by yannnnay** [comment]
Thanks for the quick answer: 
I get the following message
>docker run -it -v .\/:/opt/share 3dprintedbrain subject.nii
: invalid option
>I tried to install/run the docker on two different computers and i get a similar error. I tried chatGPT but nothing has worked so far.  I will keep yo updated

**Comment by skjerns** [comment]
Did you try using

`docker run -it -v .\/:/opt/share 3dprintedbrain subject.nii`

As it is stated in the Readme for Windows?

**Comment by yannnnay** [comment]
Yes of course. The only way i managed to make it run is going to the container, installing dos2unix and convert the script with it.

**Comment by skjerns** [comment]
Ah interesting. If you want to do a PR feel free to improve the repo :)
